keys:
  # Users
  - &user_cody age1yvzmwm4ny4qjj2scfalkxttdl3y3ehvmpscft75cf4sl7w6rr5aq4vxqh3
  # Hosts
  - &host_skyrim age1vxw6uxkv2nwajztu2msp52y8gcyv82xh8anmd54ge86l4r6l54lsa9padt
  - &host_cyrodil age18xncx98fsrz8nqtz35ytvnmzxxh7kgn3vnrnytpk6tet3jj8x5zqc0r4xm
  - &host_valenwood age14hnjzjwwv5jjk986pg2h2h335402u5fq37nnc9xunxa66lplmcaqjv90qc
creation_rules: 
  - path_regex: hosts/skyrim
    key_groups:
    - age:
      - *user_cody
      - *host_skyrim
  - path_regex: home/cody/skyrim/sops/secrets.yaml$
    key_groups:
    - age:
      - *user_cody
      - *host_skyrim
  - path_regex: hosts/cyrodil
    key_groups:
    - age:
      - *user_cody
      - *host_cyrodil
  - path_regex: home/cody/cyrodil/sops/secrets.yaml$
    key_groups:
    - age:
      - *user_cody
      - *host_cyrodil
  - path_regex: hosts/valenwood
    key_groups:
    - age:
      - *user_cody
      - *host_valenwood
  - path_regex: home/cody/valenwood/sops/secrets.yaml$
    key_groups:
    - age:
      - *user_cody
      - *host_valenwood
  - path_regex: home/cody/common/sops/secrets.yaml$
    key_groups:
    - age:
      - *user_cody
      - *host_cyrodil
      - *host_skyrim

