{
  pkgs,
  inputs,
  ...
}: {
  # TODO allow for config file to be generated by nix
  # due to some of the data being sensitive, it should be managed with sops
  home.packages = [inputs.tweather.packages.${pkgs.system}.default];
}
